// Runs once before index.js starts (see Dockerfile CMD).
//
// Baileys reads its auth state from ./session. This script restores that
// folder from the session data generated by qr-bot. Railway limits a single
// environment-variable value to 32,768 characters, so current sessions use:
//
//   SESSION_ID_PARTS=2
//   SESSION_ID_1=<first base64 chunk>
//   SESSION_ID_2=<second base64 chunk>
//
// The legacy single SESSION_ID value remains supported for existing setups.

const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

const SESSION_DIR = path.join(__dirname, 'session');
const CREDS_FILE = path.join(SESSION_DIR, 'creds.json');

function alreadyHasSession() {
    return fs.existsSync(CREDS_FILE);
}

function readSessionFromEnv() {
    const declaredCount = Number.parseInt(process.env.SESSION_ID_PARTS, 10);

    if (Number.isInteger(declaredCount) && declaredCount > 0) {
        const parts = [];
        for (let index = 1; index <= declaredCount; index += 1) {
            const value = process.env[`SESSION_ID_${index}`];
            if (!value) {
                throw new Error(`SESSION_ID_${index} is missing while SESSION_ID_PARTS is ${declaredCount}`);
            }
            parts.push(value.trim());
        }

        console.log(`[restore-session] Reassembling session from ${declaredCount} Railway-safe variable part(s).`);
        return parts.join('');
    }

    if (process.env.SESSION_ID) {
        console.log('[restore-session] Using legacy single SESSION_ID variable.');
        return process.env.SESSION_ID.trim();
    }

    return null;
}

function restoreFromEnv() {
    let serializedSession;

    try {
        serializedSession = readSessionFromEnv();
    } catch (err) {
        console.error('[restore-session] Invalid session-variable configuration:', err.message);
        return;
    }

    if (!serializedSession) {
        console.log('[restore-session] No session variables set — skipping restore.');
        console.log('[restore-session] Pair with qr-bot and add every SESSION_ID_N value to Railway.');
        return;
    }

    try {
        const zipBuffer = Buffer.from(serializedSession, 'base64');
        const zip = new AdmZip(zipBuffer);

        fs.mkdirSync(SESSION_DIR, { recursive: true });
        zip.extractAllTo(SESSION_DIR, /* overwrite */ true);

        if (fs.existsSync(CREDS_FILE)) {
            console.log('[restore-session] Session restored successfully.');
        } else {
            console.error('[restore-session] Session data was extracted but creds.json was not found.');
            console.error('[restore-session] Ensure every SESSION_ID_N value was copied without line breaks.');
        }
    } catch (err) {
        console.error('[restore-session] Failed to decode/extract session data:', err.message);
        console.error('[restore-session] The bot will still start, but will likely need re-pairing.');
    }
}

if (alreadyHasSession()) {
    console.log('[restore-session] ./session/creds.json already exists — using existing session, not touching it.');
} else {
    restoreFromEnv();
}
