// Runs once before index.js starts (see Dockerfile CMD).
//
// Baileys reads its auth state from ./session. This script restores that
// folder from the session data generated by qr-bot. Railway limits a single
// environment-variable value to 32,768 characters, so current sessions use:
//
//   SESSION_ID_PARTS=2
//   SESSION_ID_1=<first base64 chunk>
//   SESSION_ID_2=<second base64 chunk>
//
// The legacy single SESSION_ID value remains supported for existing setups.

const fs = require('fs');
const path = require('path');
const { decodeSessionArchive, extractSessionArchive } = require('./lib/sessionArchive');
const { validateRuntimeConfig } = require('./lib/runtimeConfig');

const SESSION_DIR = path.join(__dirname, 'session');
const CREDS_FILE = path.join(SESSION_DIR, 'creds.json');
const MAX_SESSION_PARTS = 32;

function alreadyHasSession() {
    return fs.existsSync(CREDS_FILE);
}

function readSessionFromEnv() {
    const declaredCount = Number.parseInt(process.env.SESSION_ID_PARTS, 10);

    if (Number.isInteger(declaredCount) && declaredCount > 0) {
        if (declaredCount > MAX_SESSION_PARTS) {
            throw new Error(`SESSION_ID_PARTS cannot exceed ${MAX_SESSION_PARTS}`);
        }
        const parts = [];
        for (let index = 1; index <= declaredCount; index += 1) {
            const value = process.env[`SESSION_ID_${index}`];
            if (!value) {
                throw new Error(`SESSION_ID_${index} is missing while SESSION_ID_PARTS is ${declaredCount}`);
            }
            parts.push(value.trim());
        }

        console.log(`[restore-session] Reassembling session from ${declaredCount} Railway-safe variable part(s).`);
        return parts.join('');
    }

    if (process.env.SESSION_ID) {
        console.log('[restore-session] Using legacy single SESSION_ID variable.');
        return process.env.SESSION_ID.trim();
    }

    return null;
}

function restoreFromEnv() {
    let serializedSession;

    try {
        serializedSession = readSessionFromEnv();
    } catch (err) {
        console.error('[restore-session] Invalid session-variable configuration:', err.message);
        return;
    }

    if (!serializedSession) {
        console.log('[restore-session] No session variables set — skipping restore.');
        console.log('[restore-session] Pair with qr-bot and add every SESSION_ID_N value to Railway.');
        return;
    }

    try {
        const zipBuffer = decodeSessionArchive(serializedSession);
        const extractedFiles = extractSessionArchive(zipBuffer, SESSION_DIR);

        if (fs.existsSync(CREDS_FILE)) {
            console.log(`[restore-session] Session restored successfully (${extractedFiles.length} protected file(s)).`);
        } else {
            console.error('[restore-session] Session data was extracted but creds.json was not found.');
            console.error('[restore-session] Ensure every SESSION_ID_N value was copied without line breaks.');
        }
    } catch (err) {
        console.error('[restore-session] Failed to decode/extract session data:', err.message);
        console.error('[restore-session] The bot will still start, but will likely need re-pairing.');
    }
}

try {
    const runtimeConfig = validateRuntimeConfig();
    if (!runtimeConfig.hasOwnerNumber) {
        console.warn('[restore-session] BOT_OWNER_NUMBER is unavailable; owner-only commands will remain disabled until it is configured.');
    }
    console.log('[restore-session] Session restore from env is disabled — starting fresh (pair via QR/pairing code).');
} catch (err) {
    console.error('[restore-session] Startup blocked:', err.message);
    process.exitCode = 1;
}
